Modified package to now use class based approach
simonepri/credential-plus pull request #10
Opened 2018-09-03 19:57 UTC by gavinhenderson

Here are the changes proposed in #9. They are by no means complete just wanted to get some opinions on the changes made so far before I put more time into tidying the code and adding more tests.

2018-09-04 15:18 UTC, simonepri commented
Hi @gavinhenderson I'll review this asap.
Thank you for the time you spent contributing!

2018-09-04 15:22 UTC, simonepri requested changes

2018-09-04 15:22 UTC, simonepri commented on index.js
> +Upash.prototype.install = function(name, algorithm) {
This should be private, we want the instance to be immutable

2018-09-04 15:22 UTC, simonepri commented on index.js
> +Upash.prototype.uninstall = function(name) {
We should remove this

2018-09-04 15:22 UTC, simonepri commented on index.js
> +Upash.prototype.use = function(name) {
This should set the default for the current instance

2018-09-05 17:44 UTC, gavinhenderson commented
@simonepri Thats those three changes made now. If you think these changes are okay let me know and I'll add more tests for the new API and I'll improve the way setting default works.

2018-10-04 07:59 UTC, gavinhenderson commented
Hey @simonepri , just wondering if there was any more changes you wanted me to make 👍

2018-10-04 19:32 UTC, simonepri commented
Hey @gavinhenderson sorry for the long delay, It looks cool.
I'll dive into this during the weekend and I'll let know you know.

Thank you for contributing!

2018-12-04 14:33 UTC, gavinhenderson commented
Hey @simonepri, I hope youre well! I noticed there hasn't been any changes on master for 4 months. Is there plans to mainain this project or should I close my pull request?

2018-12-04 15:02 UTC, simonepri commented
@gavinhenderson 
No Gavin, I'm super happy with this PR.
I'm working on a refactor for all the `phc-*` packages that `upash` relies on, and I want to finish it before merging this pr.

Sorry for the long delay.

2019-09-03 01:50 UTC, indo-dev-0 commented
Updates on this? I would like to contribute changes that would benefit from a class based system.

2019-09-03 09:44 UTC, gavinhenderson commented
@indo-dev-0 no updates from me

2019-09-08 18:02 UTC, simonepri commented
Sorry for the 1-year long delay. (I had an intense year)
I'll try to review and merge this before end of next week.

2021-02-16 15:00 UTC, closed without merging